### ISSUE TITLE
Create Kanban Board

### ISSUE THREAD

**Issue by nicupop729** [nicupop729/for_wheels_api#20]
### This issue holds the link to our Final Capstone Project

Link to GitHub repo: https://github.com/nicupop729/for_wheels/
Team members: 2
- @jonathastavares;
- @nicupop729;

Print screen of Kanban Board:
![image](https://user-images.githubusercontent.com/83596135/161123720-52dd87c9-2dcf-4860-8958-d95620a9e42e.png)

**Comment by MuriloRoque** [comment]
Hi @jonathastavares, @nicupop729,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by nicupop729** [comment]
![image](https://user-images.githubusercontent.com/83596135/161815000-1273baf0-0e41-47fa-88de-e8e3e937630f.png)
